PN-7453-componente-dialog-con-style-non-centralizzato
pagopa/pn-frontend pull request #1058
Opened 2023-11-09 14:06 UTC by ImJimMoriarty

## Short description
Replaced some `Dialog` components with `PnDialog`.

## List of changes proposed in this pull request
- replaced `DialogActions` with `PnDialogActions`
- replaced `DialogContent` with `PnDialogContent`
- replaced `Dialog with `PnDialog`

## How to test
Just `yarn start` inside PA's package and check if dialogs are correctly rendered.

2023-11-16 14:15 UTC, AndreaCimini90 reviewed
Excluding those dialog that are heavily customized, use the PnDialog

2023-11-22 10:57 UTC, ImJimMoriarty commented
I recommend doing end-to-end tests to verify whether the styles of the dialogs reflect those of the originals.
I've performed various checks, and it seems to be working, but you can never be sure about small details...

2023-11-24 10:30 UTC, AndreaCimini90 requested changes
1. There are Dialogs that aren't managed yet. Search in all the code the Dialog and replace it, where it is possible, with PnDialog
2. In ApiKeys.page, we use `<Box sx={{ minWidth: isMobile ? '0' : '600px' }}>`. I should remove it and try to use the maxWidth props on Dialog component
3. In one modal we set sx={{}}, i should try to override the style without setting an empty object

2023-11-24 10:30 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Deleghe/ConfirmationModal.tsx
> +    <PnDialog
Try to rework the modal using all the dialog components such as PnDialogActions, PnDialogTitle and so on

2023-11-24 16:07 UTC, ImJimMoriarty commented on packages/pn-commons/src/components/CodeModal/CodeModal.tsx
>    AlertTitle,
Removed `mt` from the button to eliminate excess margin.

2023-11-24 16:31 UTC, ImJimMoriarty commented on packages/pn-pa-webapp/src/components/Notifications/ConfirmCancellationDialog.tsx
>  import {
Resolved by making adjustments to the (sx) properties.

2024-01-11 15:03 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/components/Notifications/ConfirmCancellationDialog.tsx
> +    <PnDialog open={showModal} data-testid="cancel-notification-modal">
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:34 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/CancelVerificationModal.tsx
> +    <PnDialog open={open} onClose={handleClose} data-testid="cancelVerificationModal">
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:34 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactElem.tsx
> +    <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:35 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactsCodeVerification.context.tsx
> +      <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:36 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactsCodeVerification.context.tsx
> +      <PnDialog open={pecValidationOpen} data-testid="validationDialog">
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:36 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Contacts/CancelVerificationModal.tsx
> +    <PnDialog open={open} onClose={handleClose} data-testid="cancelVerificationModal">
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:36 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactElem.tsx
> +    <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:36 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactsCodeVerification.context.tsx
> +      <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:36 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactsCodeVerification.context.tsx
> +      <PnDialog open={pecValidationOpen} data-testid="validationDialog">
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:37 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Deleghe/AcceptDelegationModal.tsx
> +    <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-11 15:38 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Deleghe/AcceptDelegationModal.tsx
>          <Divider sx={{ margin: '20px 0' }} />
Margin must be 16px. Use my 2

2024-01-11 15:39 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Deleghe/AcceptDelegationModal.tsx
>              sx={{ my: 2 }}
Maybe this must be changed with mt:2

2024-01-11 15:39 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/Deleghe/ConfirmationModal.tsx
> +    <PnDialog
Checks the comments left on CodeModal about distance between Title and Content, and Content and Actions

2024-01-17 10:20 UTC, AndreaCimini90 submitted a review, later dismissed

2024-01-17 10:42 UTC, AndreaCimini90 approved these changes

2024-01-17 12:57 UTC, merged