PN-9549 - Navigation inside PP and ToS page
pagopa/pn-frontend pull request #1113
Opened 2024-01-15 14:01 UTC by alessandrogelmi

## Short description
Fix navigation inside PP and ToS page

## List of changes proposed in this pull request
- Used a function instead of hook to rewrite links

## How to test
On PF, PG and PA try to go to ToS or PP page and navigate the page through the links on the left

2024-01-15 15:54 UTC, AndreaCimini90 submitted a review, later dismissed

2024-01-15 17:12 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/PrivacyPolicy.page.tsx
>    void waitForElement('.otnotice-content').then(() => {
we can move this into the `OneTrust.NoticeApi.Initialized.then` callback. Do for all the apps

2024-01-15 17:12 UTC, AndreaCimini90 commented on packages/pn-commons/src/utility/dom.utility.ts
> -  return new Promise((resolve) => {
Maybe we can restore the old version. I strongly belive that the strict mode causes the malfunction in local environment

2024-01-16 11:28 UTC, AndreaCimini90 requested changes

2024-01-16 11:28 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/main.tsx
> +        {/* <React.StrictMode> */}
Leave a comment to explain why we commented this code.
Do for all webapp and add reference to the current issue

2024-01-16 11:28 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/PrivacyPolicy.page.tsx
> +      void waitForElement('.otnotice-content').then(() => {
move into the then callback

2024-01-16 11:28 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/TermsOfService.page.tsx
> +      void waitForElement('.otnotice-content').then(() => {
Same as before

2024-01-16 11:28 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx
> +  const configuration = useMemo(() => getConfiguration(), []);
Why the useMemo?

2024-01-16 13:11 UTC, alessandrogelmi commented on packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx
> +  const configuration = useMemo(() => getConfiguration(), []);
removed also from pa

2024-01-16 14:11 UTC, AndreaCimini90 approved these changes

2024-01-16 14:17 UTC, merged