fix: fix in products.json
pagopa/pn-frontend pull request #1130
Opened 2024-02-09 12:24 UTC by ZorbaDimatteo

2024-02-09 14:28 UTC, AndreaCimini90 approved these changes

2024-02-09 15:52 UTC, AndreaCimini90 requested changes
The problem is on the login section of the pf webapp. We don't configure the products list, but mui-italia download the list from https://selfcare.pagopa.it/assets/products.json, and this file contains the wrong url.
The products.json located in pg webapp, I think it is never used

2024-02-12 10:04 UTC, ZorbaDimatteo commented
@AndreaCimini90 yes, I'm aware of that. In fact the Jira issue correctly report that. Anyway, the product.json is used or is a backup only for some scenarios regarding pg (in particular: it is possible that in certain path under selfcare cdn our csp blocks the downloading of certain files). 
I think this pr should be approved without any changes

2024-02-13 08:27 UTC, AndreaCimini90 approved these changes

2024-02-13 09:53 UTC, merged