PN-10912 - Contacts API migrations
pagopa/pn-frontend pull request #1206
Opened 2024-05-15 10:40 UTC by alessandrogelmi

## Short description
Contacts API migrations

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-05-16 09:17 UTC, AndreaCimini90 requested changes

2024-05-16 09:17 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/redux/contact/reducers.ts
>        if (action.payload && action.payload.senderId) {
Remove the condition action.payload.senderId

2024-05-16 09:17 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/redux/contact/reducers.ts
> +            l.senderId === (action.payload as DigitalAddress).senderId &&
use action.meta.arg instead of (action.payload as DigitalAddress)

2024-05-16 13:25 UTC, alessandrogelmi commented on packages/pn-personafisica-webapp/src/redux/contact/actions.ts
> +        params.addressType as unknown as BffAddressType,
fixed by https://github.com/pagopa/pn-bff/pull/57

2024-05-17 10:13 UTC, AndreaCimini90 approved these changes

2024-05-20 07:27 UTC, AndreaCimini90 approved these changes

2024-05-20 07:43 UTC, merged