fix(PN-11950): add current organization in institutions when not present
pagopa/pn-frontend pull request #1276
Opened 2024-07-12 14:41 UTC by SarahDonvito

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-07-12 15:21 UTC, AndreaCimini90 requested changes

2024-07-12 15:21 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/App.tsx
> +    productRole: t(`roles.${role.role}`),
this is productRole: t(`roles.${institution.productRole}`)

2024-07-12 15:21 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/redux/auth/actions.ts
> +    return institutions.length > 0 &&
you missed the case of institutions.length === 0
```
const currentInstitution = {
            id: currentOrganization.id,
            name: currentOrganization.name,
            productRole: currentOrganization?.roles[0].role,
            parentName: currentOrganization?.rootParent?.description,
          },
if (institutions.length === 0) {
 return [
          currentInstitution
        ];
}
if (!institutions.some((institution) => institution.id === currentInstitution.id)) {
 return [
          ...institutions,
          currentInstitution
        ]
}
return institutions
```

2024-07-12 16:06 UTC, SarahDonvito commented on packages/pn-pa-webapp/src/redux/auth/actions.ts
> +>('getInstitutions', async (_, { rejectWithValue, getState }) => {
@AndreaCimini90 qui l'ide mi segnala errore e fallisce la compilazione

2024-07-15 07:44 UTC, AndreaCimini90 approved these changes

2024-07-15 07:51 UTC, merged