PN-11897 - Rework legal contacts components
pagopa/pn-frontend pull request #1278
Opened 2024-07-16 14:22 UTC by alessandrogelmi

## Short description
Rework legal contacts components on PF and PG

## List of changes proposed in this pull request
- Create PecContactItem component to handle editing, inserting, and validating contacts
- Removed InsertLegalContact component

## How to test
On PF and PG try to insert, remove and edit a legal contact

2024-07-17 08:13 UTC, AndreaCimini90 requested changes

2024-07-17 08:13 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/LegalContacts.tsx
> +  const defaultAddress = legalAddresses.find((a) => a.senderId === 'default');
Call it pecAddress and add the check on channelType in the find function

2024-07-17 08:13 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/__test__/LegalContacts.test.tsx
> -  it('checks invalid pec', async () => {
add the test "renders component - no contacts", copied from InsertLegalContact.test.tsx - renders InsertLegalContact

2024-07-17 08:13 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/__test__/PecContactItem.test.tsx
> +  it('type in an invalid pec', async () => {
add the test type in a valid pec copied from InsertLegalContact.test.tsx - checks valid pec

2024-07-18 10:48 UTC, alessandrogelmi commented on packages/pn-personafisica-webapp/src/components/Contacts/LegalContacts.tsx
> +        verifyingAddress={defaultAddress ? !defaultAddress.pecValid : false}
decided to keep the ternary

2024-07-18 15:01 UTC, AndreaCimini90 approved these changes

2024-07-29 09:57 UTC, merged