Feat/pn 1113 invio notifica step 2
pagopa/pn-frontend pull request #128
Opened 2022-05-11 09:58 UTC by LorenzoCocciarelli

### Description 

- Adds recipients form
- Adds formik validation
- Adds action to save in redux state
- Adds some tests

2022-05-11 10:31 UTC, AndreaCimini90 requested changes

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/FormTextField.tsx
> +import { Grid, TextField } from '@mui/material';
Aggiungere test relativo

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/PhysicalAddress.tsx
> +import { FormikErrors, FormikTouched, FormikValues } from 'formik';
Aggiungere test relativo

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +const Recipient = () => {
Usare NewNotificationCard come in PreliminaryInformations

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +              {Array.from(Array(values.recipients.length).keys()).map((recipient) => (
Non serve usare Array.from e Array.keys, il map restituisce anche l'index come secondo argomento.
Evitare comunque di utilizzare l'index come key, ma piuttosto utilizzare un id inventato.
Vedere come fatto sul branch feature/pn-1114

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/__test__/Recipient.test.tsx
> +import { act, fireEvent } from '@testing-library/react';
Aggiungere altri test. Vedere come esempio quelli del PreliminaryInformations

2022-05-11 10:31 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/utils/notification.utility.tsx
> +export const formatNotificationRecipients = (recipients: Array<FormRecipient>) =>
Aggiungere test relativo

2022-05-12 12:02 UTC, LorenzoCocciarelli commented
@AndreaCimini90 
Ho corretto secondo i commenti:
- rimosso Array.from e keys dal map dei recipients
- reintrodotta NewNotificationCard
- aggiunti i test per tutti i nuovi componenti e il file di utility

2022-05-13 07:04 UTC, AndreaCimini90 approved these changes

2022-05-13 07:11 UTC, merged