Refactor/pn 11966
pagopa/pn-frontend pull request #1293
Opened 2024-08-07 12:59 UTC by SarahDonvito

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-08-07 14:55 UTC, AndreaCimini90 approved these changes

2024-08-08 10:59 UTC, AndreaCimini90 requested changes

2024-08-08 13:02 UTC, SarahDonvito commented on packages/pn-personafisica-webapp/src/components/Contacts/PecContactItem.tsx
> +        sx={{ width: { xs: '100%', lg: '50%' } }}
without this sx, it doesn't respect the original size of the component

2024-08-08 13:10 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/components/Contacts/PecContactItem.tsx
> +        sx={{ width: { xs: '100%', lg: '50%' } }}
are you sure? I checked and it is ok. Furthermore the sx on the form, leads an error

2024-08-08 14:01 UTC, AndreaCimini90 approved these changes

2024-08-08 14:09 UTC, merged