PN-12800 - Handling virtual keys for PG users
pagopa/pn-frontend pull request #1346
Opened 2024-10-07 12:10 UTC by alessandrogelmi

## Short description
Handling virtual keys for PG users

## List of changes proposed in this pull request
- Create VirtualKeys section

## How to test
Start PG and go to "Integrazione API" section. You should see the VirtualKeys section

2024-10-09 15:44 UTC, AndreaCimini90 requested changes

2024-10-10 08:46 UTC, alessandrogelmi commented on packages/pn-personagiuridica-webapp/public/locales/it/integrazioneApi.json
> +  "rotate-subtitle": "Ruotando la chiave pubblica esistente, ne dovrai inserire una nuova e otterrai i valori di Kid e Issuer.",
No, but the modals for the Virtual Keys are not included in the Figma. I’ll try asking Norma

2024-10-10 10:17 UTC, alessandrogelmi commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/ApiKeyItemMenu.tsx
> +  keys: BffPublicKeysResponse | BffVirtualKeysResponse;
removed

2024-10-10 10:26 UTC, alessandrogelmi commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeys.tsx
> +      {!issuerState.current.tosAccepted ? (
No, because there are two different empty states. One is shown if the issuer has not accepted the ToS, and the other if there are no keys

2024-10-11 08:58 UTC, alessandrogelmi commented on packages/pn-personagiuridica-webapp/public/locales/it/integrazioneApi.json
> +  "rotate-subtitle": "Ruotando la chiave pubblica esistente, ne dovrai inserire una nuova e otterrai i valori di Kid e Issuer.",
Done

2024-10-11 12:26 UTC, AndreaCimini90 submitted a review, later dismissed

2024-10-11 14:49 UTC, AndreaCimini90 approved these changes

2024-10-11 15:37 UTC, merged