Feat/PN-12795 - Virtual key creation
pagopa/pn-frontend pull request #1350
Opened 2024-10-08 15:55 UTC by mflauti

## Short description
The code contained in this PR allow the current PG user (Administrator or simple user) to create a new virtual key, showing its value in a modal window as soon as the server response is received.

## List of changes proposed in this pull request
- Create a new virtual key for the current user

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-10-11 16:33 UTC, AndreaCimini90 requested changes
When the two change requests are fixed, the pr will be good to be merged.

@mflauti I encountered some conflicts in merging this branch with develop. Before merging can you do a check that everything you did is ok?

cc @ZorbaDimatteo

2024-10-11 16:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/PublicKeys.tsx
> +            content={<Typography>{t('dialogs.block-warning')}</Typography>}
This string is not in figma

2024-10-11 16:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeys.tsx
> +          content={<Typography>{t('dialog.block-warning')}</Typography>}
This string is not in Figma

2024-10-14 16:50 UTC, mflauti commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/PublicKeys.tsx
> +            content={<Typography>{t('dialogs.block-warning')}</Typography>}
Ok, they changed this part!

2024-10-14 16:51 UTC, mflauti commented on packages/pn-personagiuridica-webapp/src/components/IntegrazioneApi/VirtualKeys.tsx
> +          content={<Typography>{t('dialog.block-warning')}</Typography>}
See above

2024-10-15 07:06 UTC, alessandrogelmi submitted a review, later dismissed

2024-10-15 08:39 UTC, ZorbaDimatteo submitted a review, later dismissed

2024-10-15 08:57 UTC, ZorbaDimatteo approved these changes

2024-10-15 08:58 UTC, merged