Feature/pn 1401 fe accessibilita menu navigazione e contenuto principale mittente
pagopa/pn-frontend pull request #163
Opened 2022-05-31 07:33 UTC by maurizioflauti

feat: add CustomDatePicker to improve accessibility on date fields

2022-05-31 16:13 UTC, CarlaDimatteo commented
@maurizioflauti il nuovo date picker si spacca nel momento in cui invece di selezionare la data dal picker, si prova a digitare manualmente la data

2022-06-01 07:55 UTC, AndreaCimini90 requested changes

2022-06-01 07:55 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/CustomDatePicker.tsx
> +import DesktopDatePicker, { DesktopDatePickerProps } from "@mui/lab/DesktopDatePicker";
Aggiungere test relativo

2022-06-01 11:17 UTC, AndreaCimini90 approved these changes

2022-06-01 11:24 UTC, merged