Fix/pn 1638 fe deleghe dopo aver accettato una delega il menu laterale non si aggiorna
pagopa/pn-frontend pull request #241
Opened 2022-06-24 12:36 UTC by maurizioflauti

fix: fix bugs on SideMenu and Delegators components not updating properly after accept/reject a delegation

2022-06-24 15:09 UTC, AndreaCimini90 requested changes

2022-06-24 15:09 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/App.tsx
> +      children: sideMenuDelegators,
Dal codice mi sembra che adesso compaia la voce "Le tue notifiche" anche nel caso in cui non si hanno deleghe a proprio carico.
Da specifiche ricordo che il comportamento è diverso:
- niente deleghe, non compare dropdown
- deleghe, compare dropdown con voci di menu "Le tue notifiche" e i nomi di coloro che ci hanno delegato

Se non si hanno avute indicazioni su questo, confrontarsi con Damiano per confermare quanto scritto sopra

2022-06-24 15:09 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/redux/sidemenu/reducers.ts
> +    builder.addCase(acceptDelegation.fulfilled, (state) => {
Aggiungere i nuovi due casi ai test

2022-06-29 18:09 UTC, maurizioflauti commented on packages/pn-personafisica-webapp/src/redux/sidemenu/reducers.ts
> +    builder.addCase(acceptDelegation.fulfilled, (state) => {
test aggiunti

2022-06-30 09:58 UTC, merged