Feature/pn 1777 suddivisione pn commons
pagopa/pn-frontend pull request #306
Opened 2022-07-14 13:08 UTC by LorenzoCocciarelli

### Description

Suddiviso l'export in pn-commons nei diversi index.ts nelle cartelle

2022-07-15 11:28 UTC, AndreaCimini90 requested changes

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/AppMessage.tsx
> +import { IAppMessage } from '../types';
Unire i due import

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/Data/ItemsCard.tsx
> +import { Item } from '../../types';
Unire i due import

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/Data/ItemsTable.tsx
> +import { Column, Item, Sort } from '../../types';
Unire i due import

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/NotificationDetail/NotificationDetailTimelineStep.tsx
> +import { getDay, getMonthString, getTime } from '../../utils';
Non andrebbero sistemati anche gli import successivi?

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/Notifications/MobileNotificationsSort.tsx
> +import { Sort } from '../../types';
Unire i due import

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/index.ts
> +export { LoadingOverlay };
forse si può utilizzare un unico export

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/navigation/index.ts
> +export { NotFound };
Anche qui forse si può usare un solo export

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/redux/index.ts
> +import { appStateReducer } from './slices/appStateSlice';
Si posso unire gli import e gli export

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/services/index.ts
> +export { createAppError };
Si possono unire gli export

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/types/index.ts
> +export type { IAppMessage };
Forse si possono unire gli export type fra di loro e gli export fra di loro

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/utils/__test__/notification.utility.test.ts
>  } from '../../types/NotificationDetail';
Non andrebbe convertito anche qui l'import?

2022-07-15 11:28 UTC, AndreaCimini90 commented on packages/pn-commons/src/utils/index.ts
> +export { getNotificationStatusInfos };
Forse anche qui si possono unire gli export

2022-07-18 08:51 UTC, LorenzoCocciarelli commented
@AndreaCimini90 fix effetttuati

2022-07-18 10:02 UTC, AndreaCimini90 approved these changes

2022-07-18 10:28 UTC, merged