Pn 1843 fe rework pagina invio manuale notifica
pagopa/pn-frontend pull request #350
Opened 2022-08-03 08:34 UTC by NicolaGiornetta

2022-08-03 11:56 UTC, AndreaCimini90 requested changes

2022-08-03 11:56 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx
> +    fileUploaded?: any,
se non strettamente necessario, non passerei tutto il file da un componente all'altro ma solo le informazioni che servono (nel nostro caso name e size)

2022-08-03 11:59 UTC, AndreaCimini90 commented
L'approccio seguito è quello di avere due stati redux distinti. Uno per la presentazione e uno per il salvataggio della notifica. A parer mio questo rende il tutto poco manutenibile e la mia proposta è quella di utilizzare lo stato redux solo per la presentazione e adottare i cambiamenti necessari al salvataggio solo in fase di chiamata all'api

2022-08-05 15:12 UTC, ZorbaDimatteo commented
@AndreaCimini90 sono daccordo. Ho aperto il task di refactoring pn-2015

2022-08-11 15:23 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/NewNotification.page.tsx
> +    if (_.isNumber(step)) {
ho cambiato l'implementazione: se lo step è passato in input allora viene verificato che sia minore dello step attivo (per evitare di navigare in sezioni non ancora completate) e si naviga lì, altrimenti si porta l'activestep a -1.

2022-08-12 10:41 UTC, merged