Pn 1996 fe filtro per codice iun
pagopa/pn-frontend pull request #355
Opened 2022-08-03 12:37 UTC by NicolaGiornetta

2022-08-03 13:38 UTC, AndreaCimini90 requested changes

2022-08-03 13:38 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsFormBody.tsx
> +      const upperCaseValue = (e.target as HTMLInputElement).value.toUpperCase();
Il problema riguarda anche persona fisica

2022-08-03 13:38 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/Notifications/FilterNotificationsFormBody.tsx
> +      const upperCaseValue = (e.target as HTMLInputElement).value.toUpperCase();
Non dovrebbe essere necessario fare due volte l'uppercase.
In realtà se si ritorna al codice precedente, basta fare l'uppercase sulla variabile newInput

2022-08-04 14:22 UTC, ZorbaDimatteo commented
@NicolaGiornetta attenzione anche al test che fallisce 


Filter Notifications Table Component › test iunMatch input
--
107 |  
108 | expect(element).toHaveValue(mocked-iunMatch)
109 |  
110 | Expected the element to have value:
111 | mocked-iunMatch
112 | Received:
113 | MOCKED-IUNMATCH

2022-08-04 15:57 UTC, AndreaCimini90 approved these changes

2022-08-04 15:58 UTC, merged