Pn 1845 fe visualizzazione api key
pagopa/pn-frontend pull request #407
Opened 2022-09-21 12:34 UTC by NicolaGiornetta

2022-09-30 09:50 UTC, ZorbaDimatteo requested changes

2022-09-30 09:50 UTC, ZorbaDimatteo commented on packages/pn-commons/src/types/ApiKeys.ts
> +export interface ApiKey {
@NicolaGiornetta rivediamo la modellazione di questa entity seguendo questo schema https://petstore.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pn-delivery/develop/docs/openapi/api-external-b2b-pa-v1.yaml. Tipizzare status con ApiKeyStatus. Ricontrollare in generale i modelli

2022-09-30 09:50 UTC, ZorbaDimatteo commented on packages/pn-commons/src/types/ItemsTable.ts
> +  [key: string]: string | number | Array<any>;
@NicolaGiornetta perchè l'uso di any?

2022-09-30 09:50 UTC, ZorbaDimatteo commented on packages/pn-commons/src/utils/apikeys.utility.tsx
> +import { Box } from '@mui/material';
@NicolaGiornetta non ha senso che questa utility si trovi in PN commons. Le apiKey hanno scope solo sulle PA. Spostare nel package di riferimento

2022-09-30 09:50 UTC, ZorbaDimatteo commented on packages/pn-commons/src/utils/apikeys.utility.tsx
> +      {history.map((h) => {
@NicolaGiornetta in questo switch: separare la presentazione dal messaggio da mostrare. il messaggio può essere salvato in una variabile separata che viene renderizzata all'interno del componente desiderato, evitando duplicazione di codice non necessaria. Andiamo a tipizzare anche h con ApiStatusHistory

2022-09-30 10:13 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
> +          <Link>{t('subtitle.text2')}</Link>
@NicolaGiornetta il link da inserire è https://petstore.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pn-delivery/develop/docs/openapi/api-external-b2b-pa-v1.yaml#/NewNotification/sendNewNotification

2022-09-30 10:19 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
> +          <Box p={3}>
Anche qui usiamo TitleBox come componente in maniera simile a come è stato fatto sulla NewNotification.page

2022-10-04 10:41 UTC, ZorbaDimatteo requested changes

2022-10-04 10:41 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
> +      <Typography variant="h4" mb={isMobile ? 3 : 2}>
@NicolaGiornetta

2022-10-04 10:41 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
> +          <Link>{t('subtitle.text2')}</Link>
@NicolaGiornetta

2022-10-04 10:41 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
> +          <Link>{t('subtitle.text4')}</Link>
@NicolaGiornetta

2022-10-04 10:41 UTC, ZorbaDimatteo commented on packages/pn-pa-webapp/src/pages/NewApiKey.page.tsx
> +          <Box p={3}>
@NicolaGiornetta

2022-10-07 07:50 UTC, ZorbaDimatteo approved these changes

2022-10-11 15:06 UTC, AndreaCimini90 requested changes

2022-10-11 15:06 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/ApiKeys.page.tsx
> +  const [viewApiKey, setViewApiKey] = useState<null | ApiKey>();
Riflettere sulla possibilità di rifattorizzare questa parte gestendo il tutto con un solo useState e un enumeration con le varie action. Fare lo stesso per il contenuto della modale più sotto

2022-10-17 15:53 UTC, AndreaCimini90 approved these changes

2022-10-17 16:02 UTC, merged