PN-2269-fe-validazione-campi-di-input-in-invio-manuale-di-una-notifica
pagopa/pn-frontend pull request #421
Opened 2022-10-10 15:29 UTC by clombardi

## Short description
I added validations for the firstName and taxId fields in the Recipient component, the second step in the workflow to create a notification.

## List of changes proposed in this pull request
- The complete denomination of the recipient for a PF (firstName + " " + lastName) should not be longer than 80 characters, hence the sum of the lengths of firstName and lastName shouldn't exceed 79
- Tax ID should accept both 16-char and 11-digit formats for PG, only 16-char format for PF.

## How to test
Enter PA, in the Notifiche page click the button "Invia una nuova notifica", fill the first step about "Informazioni Preliminari", you should arrive to the step about "Destinatario".   
In that page you can check that the FE detect an error and disable the "Continua" button, if either the combined lengths of "Nome" and "Cognome" is more that 79, or else the "Codice Fiscale Destinatario" does not conform with the 16-char format for a CodiceFiscale.  
At the moment the "Persona Giuridica" option is disabled. If you're running the FE locally you can enable it by just finding "disabled" in `Recipient.tsx`. If you allow the selection of this option, by selecting it you should notice the following: (1) the value of "Nome" and "Cognome", or "Ragione Sociale", gets cleaned when you change from "Persona Fisica" to "Persona Giuridica" or viceversa; (2) the length of "Ragione Sociale" should not be greater than 80; and (3) that if "Persona Giuridica" is selected, both the 16-char and the 11-digit formats for Codice Fiscale should be acceptable.

2022-10-11 11:28 UTC, AndreaCimini90 requested changes

2022-10-11 14:09 UTC, clombardi commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +  // Questo stato registra il codice del fa vedere se la lunghezza della denominazione del destinatario
l'ho fatto in base a quello che hai sugerito, almeno io non percepisco un degrado nella performance

2022-10-11 14:47 UTC, clombardi commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +                          // Si accorpano tutte le modifiche da effettuare sullo stato di Formik in un unico setValues
Ciao Andrea, infatti ero sbagliato, il componente non viene re-renderizzato, ma le validazioni si eseguono più volte. 
Ho fatto tre prove mettendo un console.log dentro della validazione del `firstName` ed un altro immediatamente prima del `render` nel componente `Recipient`. 

Per ogni prova si setta nome e cognome come PF
![image](https://user-images.githubusercontent.com/5519535/195119254-1571389e-efb5-4e4a-85cc-4937ba3949f6.png)
e poi si cambia da PF a PG, analizzando cosa viene inserita nella console.

## Prova 1 - setFieldValue con settings standard
Con questa versione di `onChange`
```
onChange={(event) => {
  setFieldValue(`recipients[${index}].firstName`, "");
  if (event.currentTarget.value === RecipientType.PG) {
    setFieldValue(`recipients[${index}].lastName`, "");
  }
  setFieldValue(`recipients[${index}].recipientType`, event.currentTarget.value as RecipientType);
  trackEventByType(TrackEventType.NOTIFICATION_SEND_RECIPIENT_TYPE, {
    type: event.currentTarget.value,
  });
}}
```
Il comportamento è come di seguito
![image](https://user-images.githubusercontent.com/5519535/195120033-bcd40d72-113c-44f8-a0c9-b3ae6d05fdb5.png)
Il componente **non** viene rieseguito, ma la validazione di firstName si esegue tre volte, prendendo ad ogni turno soltanto la modifica del `setField` che l'ha lanciata.

## Prova 2 - setFieldValue con validazione evitata
Poi ho usato il terzo parametro di `setFieldValue`,  come suggerito da te
```
onChange={(event) => {
  setFieldValue(`recipients[${index}].firstName`, "", false);, 
  if (event.currentTarget.value === RecipientType.PG) {
    setFieldValue(`recipients[${index}].lastName`, "", false);
  }
  setFieldValue(`recipients[${index}].recipientType`, event.currentTarget.value as RecipientType);
  trackEventByType(TrackEventType.NOTIFICATION_SEND_RECIPIENT_TYPE, {
    type: event.currentTarget.value,
  });
}}
```
Dalla prova è risultato questo
![image](https://user-images.githubusercontent.com/5519535/195120586-89f68076-60bb-49ff-85ad-aa8838cfed5e.png)
si eseguono le validazioni solo una volta, ma le modifiche precedenti al `setFieldValue` che lancia le validazioni non sono presi in considerazione.

## Prova 3 - setValues
La terza prova è col `setValues`
```
onChange={(event) => {
  const valuesToUpdate: { recipientType: RecipientType; firstName: string; lastName?: string} = {
    recipientType: event.currentTarget.value as RecipientType, 
    firstName: '', 
  };
  if (event.currentTarget.value === RecipientType.PG) {
    /* eslint-disable-next-line functional/immutable-data */
    valuesToUpdate.lastName = '';
  }
  setValues(currentValues => {
    const updatedRecipient = {...currentValues.recipients[index], ...valuesToUpdate};
    const updatedRecipients = [
      ...currentValues.recipients.slice(0, index-1), 
      updatedRecipient, 
      ...currentValues.recipients.slice(index+1)
    ];
    return ({...currentValues, recipients: updatedRecipients});
  });
  trackEventByType(TrackEventType.NOTIFICATION_SEND_RECIPIENT_TYPE, {
    type: event.currentTarget.value,
  });
}}
```
S'è ottenuto il comportamento che si mostra di seguito
![image](https://user-images.githubusercontent.com/5519535/195122706-6ecea25d-086e-44cc-bffc-b9f52a0a4cc0.png)
Cioè, si esegue la validazione una sola volta e con tutti i valori aggiornati.

## Conclusione
Anche se per il comportamento attuale del componente, il funzionamento di più `setFieldValue` abilitando le validazioni soltanto in quello che setta `RecipientType` penso che andrebbe bene, io preferirei restare nell'opzione di un unico `setValues`, che garantisce che le validazioni vengano eseguite con tutti i valori modificati.

2022-10-12 09:19 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +                          // Si accorpano tutte le modifiche da effettuare sullo stato di Formik in un unico setValues
una soluzione alternativa potrebbe essere questa

`
const valuesToUpdate: { recipientType: RecipientType; firstName: string; lastName?: string} = {
  recipientType: event.currentTarget.value as RecipientType, 
  firstName: '', 
};
if (event.currentTarget.value === RecipientType.PG) {
  /* eslint-disable-next-line functional/immutable-data */
  valuesToUpdate.lastName = '';
}
setFieldValue(`recipients[${index}]`, {
  ...values.recipients[index],
  ...valuesToUpdate
})
`
questo dovrebbe rispettare tutti i requisiti, senza dover fare il copy di tutti i recipient e guadagnando in performance.
Se pensi possa andar bene, fai la push finale rimuovendo sia i console.log che il vecchio codice commentato

2022-10-12 15:58 UTC, clombardi commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Recipient.tsx
> +                          // Si accorpano tutte le modifiche da effettuare sullo stato di Formik in un unico setValues
L'ho fatto come suggerito, funzionato perfettamente. Grazie! 
Ho fatto anche la push finale, lascio anche l'issue Jira "In Review".

2022-10-13 11:31 UTC, AndreaCimini90 approved these changes

2022-10-13 11:49 UTC, merged