Feat/pn 2319 privacy and tos pf
pagopa/pn-frontend pull request #423
Opened 2022-10-11 07:18 UTC by LorenzoCocciarelli

## Short description
Adds Terms of Service and Privacy Policy page in PrivacyTOS.page.tsx for pn-personafisica-webapp, visible at the route /privacy-tos

## List of changes proposed in this pull request
- Adds routing to TOS and Privacy page
- Adds TOS and Privacy page
- Changes links to privacy and tos to pointo to the new route 

## How to test
- Go to the route /privacy-tos and check that two accordions one containing the terms of service and the other the privacy policy.
- Check that links that point to "Termini di Servizio" o "Privacy Policy" bring to the TOS and privacy page

2022-10-11 14:09 UTC, AndreaCimini90 requested changes

2022-10-11 14:09 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/Layout/Layout.tsx
> -        <Header
Valutare se è il caso di creare un componente di Layout per quelle pagine che non richiedono header, footer e sidebar oppure se aggiungere due flag showHeader e showFooter al posto di showLayout.
Usare un componente Layout e poi avere un flag showLayout interno che lo nasconde quasi del tutto, a mio parere può generare confusione.
Discuterne anche con Carlotta

2022-10-11 14:12 UTC, AndreaCimini90 commented
Ci sono degli errori quando si lancia l'applicazione lato pa e lato pf-login. In generale quando si modifica qualcosa presente in commons, fare un giro su tutte le applicazioni che usano i componenti modificati.
AppType se non più utilizzato rimuoverlo da pn-commons

2022-10-12 14:16 UTC, LorenzoCocciarelli commented
rimosso apptype e relativi errori dovuti alle props passate a layout

2022-10-12 15:49 UTC, AndreaCimini90 approved these changes

2022-10-13 07:04 UTC, merged