Feat/pn 2298 add tos guard
pagopa/pn-frontend pull request #442
Opened 2022-10-24 12:12 UTC by LorenzoCocciarelli

## Short description
Introduces ToSGuard and remove tos as route, both in pa and personafisica.

## List of changes proposed in this pull request
- Adds ToSGuard in routes
- Adds tests

## How to test
If the user has not accepted the tos, the tos acceptance page should be displayed, otherwise the current page should be displayed.
The route should not change
While fetching the tos value the loading page should be displayed.

2022-11-02 15:02 UTC, AndreaCimini90 requested changes

2022-11-02 15:02 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/App.tsx
> +  useEffect(() =>{
Facendo delle prove, al primo login si ha un errore in quanto viene chiamata la tos senza essere autenticato.
Non si può spostare la getTosApproval nel TosGuard? Se si applicare lo stesso cambiamento a persona fisica

2022-11-07 10:16 UTC, LorenzoCocciarelli commented
Description:
- Aligned position of ToSGuard between pn-pa-webapp e pn-personafisica-webapp
- Fixed merge conflict
- Fixed tests

2022-11-07 10:42 UTC, AndreaCimini90 approved these changes

2022-11-07 11:04 UTC, merged