refactor: edit useIsMobile hook to use useMediaQuery from mui
pagopa/pn-frontend pull request #508
Opened 2022-12-13 14:06 UTC by leleOFA

chore: install css-mediaquery dev dependency with @types for testing purpose

## Short description
with the changes made it occurs that if the application is in mobile mode based on a mui hook and no longer based on the window size

## List of changes proposed in this pull request
- I entered the useMediaQuery hook referring to the control dimension with breakpoints
- I inserted in the tests a method of the css-mediaquery dependency which controls the size of the screen

## How to test
to test the refactoring change width of window initially over 1200px for desktop mode while for the mobile mode set width under 1200px

2022-12-15 13:34 UTC, clombardi commented
I'm looking this PR.

2022-12-15 17:23 UTC, clombardi requested changes
The changes in both functionality and tests are in general OK, there are just some details to be checked.

2022-12-16 13:49 UTC, leleOFA commented on packages/pn-personafisica-login/src/pages/login/__tests__/Login.test.tsx
> +import React from 'react';
I placed them at the top

2022-12-16 14:06 UTC, leleOFA commented on packages/pn-personafisica-webapp/src/component/Contacts/__test__/DigitalContactElem.test.tsx
> +    userEvent.click(buttons![1]);
the docs that you see is for user-event@14, but we use user-event@13.5 and the setup() method is not present in this version

2022-12-16 14:32 UTC, clombardi approved these changes
OK, ready to merge.

2022-12-16 18:12 UTC, merged