Pn 2987 fe visualizzare l aar nella pagina di dettaglio della notifica
pagopa/pn-frontend pull request #539
Opened 2023-01-10 09:56 UTC by NicolaGiornetta

## Short description
Added other documents (AAR) box in detailed notification.

## List of changes proposed in this pull request
- Other documents box for PA
- Other documents box for PF

## How to test
Almost all notifications have AAR documents, so just pick one (both PA or PF). Cancelled notifications in PA show disabled downloads link.

2023-01-10 14:59 UTC, ZorbaDimatteo requested changes
@NicolaGiornetta from what I see, this new component NotificationDetailOtherDocument is slightly similar to NotificationDetailDocument.
I don't see it as necessary at all. So I suggest to use the existent NotificationDetailDocument working on NotificationDetail page

2023-01-10 15:01 UTC, ZorbaDimatteo commented on packages/pn-commons/src/utils/notification.utility.ts
> +  if (timelineFiltered.length>0) {
@NicolaGiornetta format this file

2023-01-13 12:14 UTC, maurizioflauti requested changes

2023-01-16 08:16 UTC, NicolaGiornetta commented on packages/pn-commons/src/types/NotificationDetail.ts
> +  documentId?: string;
docIdx is used as index for recipient documents. documentId is the identifier user for aar documents. APIs are working different,

2023-01-18 11:21 UTC, maurizioflauti approved these changes

2023-01-18 14:07 UTC, ZorbaDimatteo approved these changes

2023-01-18 16:41 UTC, maurizioflauti approved these changes

2023-01-18 16:45 UTC, merged