Fix/pn 3802
pagopa/pn-frontend pull request #576
Opened 2023-01-31 15:32 UTC by leleOFA

## Short description
fix see ToS and Privacy policy with an user unauthorized

## List of changes proposed in this pull request
- create proposed hook
- used in  fees page 

## How to test
when click in menù navigation you don't see login page

2023-02-02 15:21 UTC, AndreaCimini90 requested changes

2023-02-02 15:21 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/TermsOfService.page.tsx
> +      setContentLoaded(true);
Same as before

2023-02-02 15:21 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/TermsOfService.page.tsx
> +      setContentLoaded(true);
Same as before

2023-02-02 15:35 UTC, leleOFA commented on packages/pn-commons/src/hooks/useDocumentationUnauthorized.ts
> +      const links = document.querySelectorAll('.otnotice-content a');
do it

2023-02-02 15:37 UTC, leleOFA commented on packages/pn-pa-webapp/src/pages/PrivacyPolicy.page.tsx
> +      setContentLoaded(true);
do it for all

2023-02-02 16:20 UTC, ZorbaDimatteo commented on packages/pn-commons/src/hooks/useDocumentationUnauthorized.ts
> +export const useDocumentationUnauthorized = (contentLoaded: boolean, route: any) => {
@AndreaCimini90 I like it!

2023-02-02 16:23 UTC, leleOFA commented on packages/pn-commons/src/hooks/useDocumentationUnauthorized.ts
> +export const useDocumentationUnauthorized = (contentLoaded: boolean, route: any) => {
i rename it

2023-02-03 10:09 UTC, AndreaCimini90 approved these changes

2023-02-03 10:24 UTC, AndreaCimini90 approved these changes

2023-02-03 10:37 UTC, merged