Refactor/pn 3948
pagopa/pn-frontend pull request #593
Opened 2023-02-14 11:29 UTC by leleOFA

## Short description
create env variable which allow switch payment to enabled at disabled
## List of changes proposed in this pull request
- create env variable
- create conditions when env is true or false
- arrived in attachments page, if env variable is false, we proceed to send new notification

## How to test
if the variable is false there is no choice of payment and the notification is created just after inserting the attachments

2023-02-14 15:05 UTC, AndreaCimini90 requested changes

2023-02-14 15:05 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/components/NewNotification/Attachments.tsx
> +      if (!IS_PAYMENT_ENABLED) {
This sound strange to me.
I would expect this workflow:
- form is valid (formik.isValid)?
  - No -> do nothing
  - Yes -> continue to the next point
- isCompleted and !IS_PAYMENT_ENABLED?
  - No -> do the two dispatches
  - Yes -> call onConfirm and don't call two dispatches

2023-02-14 15:36 UTC, leleOFA commented on packages/pn-pa-webapp/buildspec.yaml
> +          REACT_APP_IS_PAYMENT_ENABLED: false
fix it

2023-02-17 08:42 UTC, AndreaCimini90 approved these changes

2023-02-17 08:45 UTC, merged