Feature/pn 976 modale conferma delega
pagopa/pn-frontend pull request #64
Opened 2022-03-29 12:32 UTC by LorenzoCocciarelli

### Descritpion

- Add modal to input verification code and accept modal
- Add delegator name to accept button to show delegator identity in modal
- Add translations for delegation modal
- Add state management to accept delegation

2022-03-30 10:13 UTC, CarlaDimatteo requested changes
@LorenzoCocciarelli attenzione in particolare agli any e a nomi di variabili poco parlanti

2022-03-30 10:13 UTC, CarlaDimatteo commented on packages/pn-personafisica-webapp/src/api/delegations/Delegations.api.ts
>    createDelegation: (data: any): Promise<CreateDelegationProps | 'error'> =>
esiste il model per data?

2022-03-30 11:57 UTC, LorenzoCocciarelli commented on packages/pn-personafisica-webapp/src/api/delegations/Delegations.api.ts
>    createDelegation: (data: any): Promise<CreateDelegationProps | 'error'> =>
Sì, verrà implementato nelle task di collegamento alle API

2022-03-31 07:31 UTC, CarlaDimatteo approved these changes

2022-03-31 07:31 UTC, merged