fix: fix a11y in emptystate
pagopa/pn-frontend pull request #861
Opened 2023-06-27 10:04 UTC by leleOFA

## Short description
fix a11y in emptystate
## List of changes proposed in this pull request
- insert tab index and arialabel in typography

## How to test
using voiceover see you empty state table

2023-06-28 16:43 UTC, AndreaCimini90 requested changes

2023-06-28 16:43 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/EmptyState.tsx
> +              component="p"
component="p" is useless

2023-06-28 16:43 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/EmptyState.tsx
> +            component="p"
as before

2023-06-28 16:43 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/EmptyState.tsx
> +            component="p"
as before

2023-07-03 09:07 UTC, leleOFA commented on packages/pn-commons/src/components/EmptyState.tsx
> +              component="p"
delete it

2023-07-03 09:07 UTC, leleOFA commented on packages/pn-commons/src/components/EmptyState.tsx
> +            component="p"
delete it

2023-07-03 09:10 UTC, leleOFA commented on packages/pn-commons/src/components/EmptyState.tsx
> +            component="p"
delete it

2023-07-03 11:16 UTC, AndreaCimini90 approved these changes

2023-07-03 11:16 UTC, merged