fix: removed email icon from breadcrumb and fixed mobile alignment
pagopa/pn-frontend pull request #890
Opened 2023-07-05 12:49 UTC by alessandrogelmi

## Short description
Removed icons from breadcrumb of notification detail. Fixed also mobile alignment of breadcrumb

## List of changes proposed in this pull request
- Removed icon from breadcrum
- Fixed mobile alignment

## How to test
Go to notification detail of PA, PF and PG and breadcrumb shouldn't have the email icon. On mobile it should be inline

2023-07-05 12:50 UTC, alessandrogelmi commented
[PN-6086](https://pagopa.atlassian.net/browse/PN-6086)
[PN-6622](https://pagopa.atlassian.net/browse/PN-6622)
[PN-6731](https://pagopa.atlassian.net/browse/PN-6731)

2023-07-07 08:20 UTC, AndreaCimini90 requested changes

2023-07-07 08:20 UTC, AndreaCimini90 commented on packages/pn-pa-webapp/src/pages/NotificationDetail.page.tsx
> +      linkLabel={<Fragment>{t('detail.breadcrumb-root', { ns: 'notifiche' })}</Fragment>}
Remove fragment

2023-07-07 08:20 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/NotificationDetail.page.tsx
> +        linkLabel={<Fragment>{t('detail.breadcrumb-root', { ns: 'notifiche' })}</Fragment>}
Same as before

2023-07-07 08:20 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
> +        linkLabel={<Fragment>{t('detail.breadcrumb-root', { ns: 'notifiche' })}</Fragment>}
Same as before

2023-07-07 09:59 UTC, AndreaCimini90 approved these changes

2023-07-07 10:22 UTC, merged