Pn 6205 fe import dei testi tradotti nelle webapp
pagopa/pn-frontend pull request #916
Opened 2023-07-17 08:26 UTC by NicolaGiornetta

## Short description
Added new languages support.

## List of changes proposed in this pull request
- Added new translation JSONs
- Fixed some components to properly update when change languages
- Fixed a couple of tests

## How to test
Switch between languages to see effects.

2023-07-21 13:33 UTC, AndreaCimini90 requested changes
@NicolaGiornetta in the login webapp the header and the footer component have localizations missed for those languages other than italian

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Contacts/LegalContactsList.tsx
> +    [legalAddresses, i18n.language]
Are we sure that i18n.language dependency is needed?

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Contacts/LegalContactsList.tsx
> +    [legalAddresses, i18n.language]
as before

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Deleghe/Delegates.tsx
> +        return <Chip label={t(`deleghe.table.${value}`)} color={color} />;
why did you remove the data-testid?

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Deleghe/Delegates.tsx
> +        const { color } = getDelegationStatusLabelAndColor(value as DelegationStatus);
Try to move the localization into the getDelegationStatusLabelAndColor function

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Deleghe/Delegators.tsx
> +          return <Chip label={t(`deleghe.table.${value}`)} color={color} data-testid={`statusChip-${label}`} />;
Same as before

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Deleghe/MobileDelegates.tsx
> +        return <Chip label={t(`deleghe.table.${value}`)} color={color} />;
Same as before

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Deleghe/MobileDelegators.tsx
> +          return <Chip label={t(`deleghe.table.${value}`)} color={color} />;
Same as before

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegatesByCompany.tsx
> +        const { color } = getDelegationStatusLabelAndColor(value as DelegationStatus);
Same as for PF

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/component/Deleghe/DelegationsOfTheCompany.tsx
> +          return <Chip label={t(`deleghe.table.${value}`)} color={color} />;
Same as for PF

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/component/Contacts/LegalContactsList.tsx
> +    [legalAddresses, i18n.language]
Same as for PF

2023-07-21 13:33 UTC, AndreaCimini90 commented on packages/pn-personagiuridica-webapp/src/component/Contacts/LegalContactsList.tsx
> +    [legalAddresses, i18n.language]
Same as for PF

2023-07-24 07:04 UTC, NicolaGiornetta commented on packages/pn-personafisica-webapp/src/component/Deleghe/Delegates.tsx
> +        return <Chip label={t(`deleghe.table.${value}`)} color={color} />;
Because wasn't used in any test.

2023-07-25 14:13 UTC, AndreaCimini90 approved these changes

2023-07-25 15:17 UTC, merged