fix: fixed inline link of digital contacts code verification modal
pagopa/pn-frontend pull request #922
Opened 2023-07-18 10:04 UTC by alessandrogelmi

## Short description
Fixed inline link of digital contacts code verification modal

## List of changes proposed in this pull request
- Replaced ButtonNaked with Box in order to apply display inline 

## How to test
Go to "Recapiti" Page of PF and PG and try to insert an email or phone number. On the modal you should see the link "generane uno nuovo" inline

2023-07-18 10:05 UTC, alessandrogelmi commented
[PN-6720](https://pagopa.atlassian.net/browse/PN-6720) the other bug reported was resolved on another PR

2023-07-20 12:04 UTC, AndreaCimini90 requested changes

2023-07-20 12:04 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Contacts/DigitalContactsCodeVerification.context.tsx
> +              <Box
For the accessibility this can be a problem. Use ButtonNaked but set the property "component" as "Box"

2023-07-20 13:26 UTC, AndreaCimini90 approved these changes

2023-07-20 13:37 UTC, merged