feat: payment box component
pagopa/pn-frontend pull request #944
Opened 2023-08-04 14:04 UTC by alessandrogelmi

## Short description
Implemented payment Box component

## List of changes proposed in this pull request
- Payment box in notificationDetail

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-08-07 09:14 UTC, AndreaCimini90 requested changes

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
> +        )}{' '}
replace {' '} whit it's html analogus

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
> +        Paga
Localize it

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
> -    expect(result.container).toHaveTextContent(/Payment/i);
this expect should be still valid

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
>    test('renders NotificationDetail page without payment box if noticeCode is empty', async () => {
change the text and the test with new logic
`{ recipients: [{ payment: { noticeCode: '' } }] }`
is not valid
`{ recipients: [{ payments: [] / null }] }`
is a valid case

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
>    apiOutcomeTestHelper,
use the mock in mocks folder

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
> -    result = await renderComponent(overrideNotificationMock({recipients: [{payment: { creditorTaxId: '' }}]}));
as before, change the test. the previous test can be payments null and this one can be payments empty

2023-08-07 09:14 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
> -    result = await renderComponent(overrideNotificationMock({recipients: [{payment: { creditorTaxId: '', noticeCode: '' }}]}));
as before, we don't have payment any more

2023-08-07 09:37 UTC, alessandrogelmi commented on packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
> +        )}{' '}
`&nbsp;` this one?

2023-08-07 09:44 UTC, AndreaCimini90 commented on packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
> +        )}{' '}
yes

2023-08-07 11:48 UTC, alessandrogelmi commented on packages/pn-commons/src/components/NotificationDetail/NotificationPaymentRecipient.tsx
> +  console.log(loading);
Skeleton will be in children component

2023-08-08 09:54 UTC, AndreaCimini90 approved these changes

2023-08-08 14:01 UTC, AndreaCimini90 approved these changes

2023-08-09 08:00 UTC, AndreaCimini90 requested changes

2023-08-09 08:36 UTC, AndreaCimini90 approved these changes

2023-08-09 08:37 UTC, merged