Fix/pn 7763
pagopa/pn-frontend pull request #978
Opened 2023-09-12 10:27 UTC by leleOFA

## Short description
delete filter with cancellation in progress
## List of changes proposed in this pull request
- delete filter with cancellation in progress
- delete fetch paymentinfo when notification is cancelled
- fix test with fetch payment info

## How to test
in dashbaord pa not view filter with status 'cancellation in progress'

2023-09-12 13:10 UTC, AndreaCimini90 requested changes

2023-09-12 13:10 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
>    // Questo test fallisce per un bug nel dettaglio notifica. La paymentInfo viene chiamata anche se la notifica è in stato annullata
remove the comments

2023-09-12 13:10 UTC, AndreaCimini90 commented on packages/pn-personafisica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
> -  it.skip('renders payment when notification is CANCELLED', async () => {
Do the things under COSE DA FARE

2023-09-12 13:13 UTC, leleOFA commented on packages/pn-personafisica-webapp/src/pages/__test__/NotificationDetail.page.test.tsx
>    // Questo test fallisce per un bug nel dettaglio notifica. La paymentInfo viene chiamata anche se la notifica è in stato annullata
done

2023-09-13 10:07 UTC, leleOFA commented on packages/pn-personafisica-webapp/src/component/Notifications/__test__/NotificationPayment.test.tsx
> -  it.skip('renders payment when notification is CANCELLED', async () => {
do it

2023-09-13 16:43 UTC, merged