Payments with cancelled notification - PN-7507
pagopa/pn-frontend pull request #996
Opened 2023-09-26 08:55 UTC by alessandrogelmi

## Short description
Payments handling when notification is cancelled

## List of changes proposed in this pull request
- Payments handling when notification is cancelled

2023-09-27 23:53 UTC, clombardi requested changes
In general the changes are OK, and indeed they configure a solution fit for the problem at hand and regarding the implementation for the multi-payment feature.
I added some minor comments that IMHO would be convenient to address before merging this PR.

2023-09-28 06:30 UTC, alessandrogelmi commented on packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
> +    if (checkIfUserHasPayments && !(isCancelled.cancelled || isCancelled.cancellationInProgress)) {
If notification is cancelled we don't have to get data from ext-registries. So, we include only the data from the timeline (noticeCode and creditorTaxId)

2023-09-28 08:36 UTC, clombardi commented on packages/pn-personagiuridica-webapp/src/pages/NotificationDetail.page.tsx
> +    if (checkIfUserHasPayments && !(isCancelled.cancelled || isCancelled.cancellationInProgress)) {
Indeed this is indicated in the JIRA Issue.

2023-09-28 09:04 UTC, clombardi commented on packages/pn-personagiuridica-webapp/src/__mocks__/NotificationDetail.mock.ts
> +    details: {
Done after having agreed on this with Alessandro.

2023-09-28 09:06 UTC, clombardi approved these changes
All minor points signaled were addressed, now this PR is ready to review.

2023-09-28 09:15 UTC, merged